import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "@/layouts/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={
          "min-w-full min-h-screen px-5 md:px-6 lg:px-8 pb-5 md:pb-6 lg:pb-8 "
        }
      >
        <MainLayout children={children} />
      </body>
    </html>
  );
}
